### ISSUE TITLE
Decimater fails on large obj file (35 Mb)

### ISSUE THREAD

**Issue by AlexeyMakarov1** [songrun/SeamAwareDecimater#8]
Hello songrun,

A great tool you developed!

I have an issue working with Decimater.
It fails on heavy obj models (tried 35 Mb and more), though works for smaller models (< 20 Mb).
The last model I tried (with options 'percent-vertices 50') failed with 
![image](https://user-images.githubusercontent.com/42264335/43944359-443c33e8-9c87-11e8-8a77-26f9aeab9e7b.png)

The model itself: 
[Large.zip](https://github.com/songrun/SeamAwareDecimater/files/2276955/Large.zip)

OS: Centos7 x86_64. IDE: CLion

Could you please help to resolve this issue?

Regards,
Alexey

**Comment by songrun** [comment]
Hey Alexey,

Thank you for your interests. 

Currently the project are only supposed to handle one-piece component 3D model with non-overlapped UV. 

The model you sent me satisfies neither of these two conditions. So I’m not surprised it failed. I don’t think size is relevant here.(Maybe I’m wrong)

If you must use this model, I suggest that either you alter the code(which may need a lot of work), or break down original model to several standalone pieces. After simplifying each piece, then you put them back together.
I know this is a pain. But I’m afraid that’s how it works.

---------------------------------------------
Best,
Songrun Liu

**Comment by AlexeyMakarov1** [comment]
Thank you for the response.

Seems that I missed restriction about 'one-piece component 3D model with non-overlapped UV'.

Best regards,
Alexey
